local opt = vim.opt
opt.encoding = "utf-8"
opt.fileencodings = "utf-8 GBK"
opt.tabstop = 4
opt.softtabstop = 4
opt.shiftwidth = 4
opt.shiftround = true
opt.ignorecase = true
opt.smartcase = true
opt.hlsearch = false
opt.incsearch = true
opt.mouse = "a"
opt.relativenumber = true
opt.number = true
opt.background = "dark"
opt.clipboard = "unnamedplus"
opt.spell = true
opt.spelllang = { "en_us" }
opt.autowrite = true
opt.completeopt = "menu,menuone,noselect"
opt.cursorline = true
vim.loader.enable()
