vim.loader.enable()
local opt = {
	encoding = "utf-8",
	fileencodings = "utf-8 GBK",
	tabstop = 4,
	softtabstop = 4,
	shiftwidth = 4,
	shiftround = true,
	ignorecase = true,
	smartcase = true,
	smartindent = true,
	hlsearch = false,
	incsearch = true,
	mouse = "a",
	relativenumber = true,
	number = true,
	background = "dark",
	clipboard = "unnamedplus",
	spell = true,
	spelllang = { "en_us" },
	autowrite = true,
	completeopt = "menu,menuone,noselect",
	cursorline = true,
	splitbelow = true,
	splitkeep = "screen",
	splitright = true,
	list = true,
	expandtab = true,
	virtualedit = "block",
	wildmode = "longest:full,full",
	backup = false,
	showmode = false,
	swapfile = false,
	undofile = true,
	signcolumn = "yes",
}
for k, v in ipairs(opt) do
	vim.opt[k] = v
end
