return {
  "stevearc/conform.nvim",
  event = "BufWritePre",
  opts = {
    default_format_opts = { timeout_ms = 500, lsp_format = "fallback" },
    formatters = { sqlfluff = { inherit = true, args = { "format", "--dialect=postgres", "-" } } },
    formatters_by_ft = {
      lua = { "stylua" },
      c = { "clang-format" },
      cpp = { "clang-format" },
      cmake = { "cmake_format" },
      rust = { "rustfmt" },
      nix = { "nixfmt" },
      yaml = { "prettier" },
      toml = { "taplo" },
      python = { "ruff_fix", "ruff_format", "ruff_organize_imports" },
      sh = { "shfmt" },
      makrdown = { "prettier" },
      html = { "prettier" },
      css = { "prettier" },
      javascript = { "prettier" },
      typescript = { "prettier" },
      tex = { "latexindent" },
      sql = { "sqlfluff" },
      typst = { "typstyle" },
      java = { "google-java-format" },
      fish = { "fish_indent" },
      vue = { "prettier" },
      astro = { "prettier" },
    },
    format_on_save = { timeout_ms = 100 },
  },
}
