---@type LazyPluginSpec
return {
  "stevearc/conform.nvim",
  event = "BufWritePre",
  opts = {
    default_format_opts = { timeout_ms = 500, lsp_format = "fallback" },
    formatters_by_ft = {
      lua = { "stylua" },
      c = { "clang-format" },
      cpp = { "clang-format" },
      cmake = { "cmake_format" },
      rust = { "rustfmt" },
      yaml = { { "prettier", timeout_ms = 1000 }, "dprint" },
      json = { { "prettier", timeout_ms = 1000 }, "dprint" },
      toml = { "taplo" },
      python = { "ruff_fix", "ruff_format", "ruff_organize_imports" },
      sh = { "shfmt" },
      makrdown = { { "prettier", timeout_ms = 1000 }, "dprint" },
      html = { "prettier", timeout_ms = 1000 },
      css = { "prettier", timeout_ms = 1000 },
      javascript = { "prettier", timeout_ms = 1000 },
      typescript = { "prettier", timeout_ms = 1000 },
      tex = { "latexindent" },
      sql = { "sqlfluff" },
      typst = { "typstyle" },
      java = { "google-java-format" },
      fish = { "fish_indent" },
      vue = { "prettier", timeout_ms = 1000 },
      astro = { "prettier", timeout_ms = 1000 },
      terraform = { "terraform_fmt" },
      go = { "golines" },
      haskell = { "ormolu" },
    },
    format_on_save = {},
  },
}
